; =========================================================================
; === PlatformIO Proje Konfigürasyonu (Raspberry Pi Pico W) ===
; =========================================================================

[platformio]
    extra_configs = secrets.ini
    default_envs = picow

; =========================================================================
; === Global Build Flags (Tüm Environment'lar için) ===
; =========================================================================
[env]
    ; --- Global Hardware Defaults ---
    board_build.filesystem_size = 128K
    
    ; --- Global Build Configuration ---
    build_type = release
    
    ; --- Global Monitor Settings ---
    monitor_speed = 115200
    
    ; --- Kod kalitesi bayrakları - tüm kaynak kodlar için ---
    build_src_flags = 
        -Wall
        -Wextra
        -Wswitch-default

    ; --- Ortak derleme bayrakları - tüm environment'lar için ---
    build_flags =
        -Ofast
        -std=gnu++20
        
        -D SERIAL_BAUD=115200
        -D SERIAL_WAIT_MS=3000
        
        -D WIFI_STA_SSID=\"${wifi.sta_ssid}\"
        -D WIFI_STA_PASS=\"${wifi.sta_pass}\"
        -D WIFI_AP_SSID=\"${wifi.ap_ssid}\"
        -D WIFI_AP_PASS=\"${wifi.ap_pass}\"

; =========================================================================
; === Raspberry Pi Pico W Environment ===
; =========================================================================
[env:picow]
    ; --- Platform & Board ---
    platform = https://github.com/maxgerhardt/platform-raspberrypi.git
    board = rpipicow
    framework = arduino

    ; --- Performance & Hardware ---
    board_build.f_cpu = 200000000L

    ; --- Monitor & Upload ---
    monitor_speed = 2000000  ; Override global - yüksek hız
    upload_protocol = picotool

    ; --- Environment Specific Flags ---
    build_unflags = 
        -D SERIAL_BAUD=115200

    build_flags = 
        -D PIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH

        ${env.build_flags}
        -D SERIAL_BAUD=2000000  ; Environment specific - yüksek hız